// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -typed -source=interfaces.go -destination=mocks_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	io "io"
	reflect "reflect"

	malgo "github.com/gen2brain/malgo"
	gomock "go.uber.org/mock/gomock"
)

// MockConnection is a mock of Connection interface.
type MockConnection struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionMockRecorder
	isgomock struct{}
}

// MockConnectionMockRecorder is the mock recorder for MockConnection.
type MockConnectionMockRecorder struct {
	mock *MockConnection
}

// NewMockConnection creates a new mock instance.
func NewMockConnection(ctrl *gomock.Controller) *MockConnection {
	mock := &MockConnection{ctrl: ctrl}
	mock.recorder = &MockConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnection) EXPECT() *MockConnectionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConnection) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockConnectionMockRecorder) Close() *MockConnectionCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConnection)(nil).Close))
	return &MockConnectionCloseCall{Call: call}
}

// MockConnectionCloseCall wrap *gomock.Call
type MockConnectionCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConnectionCloseCall) Return(arg0 error) *MockConnectionCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConnectionCloseCall) Do(f func() error) *MockConnectionCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConnectionCloseCall) DoAndReturn(f func() error) *MockConnectionCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadMessage mocks base method.
func (m *MockConnection) ReadMessage() (int, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMessage")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadMessage indicates an expected call of ReadMessage.
func (mr *MockConnectionMockRecorder) ReadMessage() *MockConnectionReadMessageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMessage", reflect.TypeOf((*MockConnection)(nil).ReadMessage))
	return &MockConnectionReadMessageCall{Call: call}
}

// MockConnectionReadMessageCall wrap *gomock.Call
type MockConnectionReadMessageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConnectionReadMessageCall) Return(messageType int, p []byte, err error) *MockConnectionReadMessageCall {
	c.Call = c.Call.Return(messageType, p, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConnectionReadMessageCall) Do(f func() (int, []byte, error)) *MockConnectionReadMessageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConnectionReadMessageCall) DoAndReturn(f func() (int, []byte, error)) *MockConnectionReadMessageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WriteJSON mocks base method.
func (m *MockConnection) WriteJSON(v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteJSON", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteJSON indicates an expected call of WriteJSON.
func (mr *MockConnectionMockRecorder) WriteJSON(v any) *MockConnectionWriteJSONCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteJSON", reflect.TypeOf((*MockConnection)(nil).WriteJSON), v)
	return &MockConnectionWriteJSONCall{Call: call}
}

// MockConnectionWriteJSONCall wrap *gomock.Call
type MockConnectionWriteJSONCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConnectionWriteJSONCall) Return(arg0 error) *MockConnectionWriteJSONCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConnectionWriteJSONCall) Do(f func(any) error) *MockConnectionWriteJSONCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConnectionWriteJSONCall) DoAndReturn(f func(any) error) *MockConnectionWriteJSONCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WriteMessage mocks base method.
func (m *MockConnection) WriteMessage(messageType int, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteMessage", messageType, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessage indicates an expected call of WriteMessage.
func (mr *MockConnectionMockRecorder) WriteMessage(messageType, data any) *MockConnectionWriteMessageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessage", reflect.TypeOf((*MockConnection)(nil).WriteMessage), messageType, data)
	return &MockConnectionWriteMessageCall{Call: call}
}

// MockConnectionWriteMessageCall wrap *gomock.Call
type MockConnectionWriteMessageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConnectionWriteMessageCall) Return(arg0 error) *MockConnectionWriteMessageCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConnectionWriteMessageCall) Do(f func(int, []byte) error) *MockConnectionWriteMessageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConnectionWriteMessageCall) DoAndReturn(f func(int, []byte) error) *MockConnectionWriteMessageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockAudioSystem is a mock of AudioSystem interface.
type MockAudioSystem struct {
	ctrl     *gomock.Controller
	recorder *MockAudioSystemMockRecorder
	isgomock struct{}
}

// MockAudioSystemMockRecorder is the mock recorder for MockAudioSystem.
type MockAudioSystemMockRecorder struct {
	mock *MockAudioSystem
}

// NewMockAudioSystem creates a new mock instance.
func NewMockAudioSystem(ctrl *gomock.Controller) *MockAudioSystem {
	mock := &MockAudioSystem{ctrl: ctrl}
	mock.recorder = &MockAudioSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudioSystem) EXPECT() *MockAudioSystemMockRecorder {
	return m.recorder
}

// Devices mocks base method.
func (m *MockAudioSystem) Devices(kind malgo.DeviceType) ([]malgo.DeviceInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Devices", kind)
	ret0, _ := ret[0].([]malgo.DeviceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Devices indicates an expected call of Devices.
func (mr *MockAudioSystemMockRecorder) Devices(kind any) *MockAudioSystemDevicesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Devices", reflect.TypeOf((*MockAudioSystem)(nil).Devices), kind)
	return &MockAudioSystemDevicesCall{Call: call}
}

// MockAudioSystemDevicesCall wrap *gomock.Call
type MockAudioSystemDevicesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAudioSystemDevicesCall) Return(arg0 []malgo.DeviceInfo, arg1 error) *MockAudioSystemDevicesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAudioSystemDevicesCall) Do(f func(malgo.DeviceType) ([]malgo.DeviceInfo, error)) *MockAudioSystemDevicesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAudioSystemDevicesCall) DoAndReturn(f func(malgo.DeviceType) ([]malgo.DeviceInfo, error)) *MockAudioSystemDevicesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockServerConnector is a mock of ServerConnector interface.
type MockServerConnector struct {
	ctrl     *gomock.Controller
	recorder *MockServerConnectorMockRecorder
	isgomock struct{}
}

// MockServerConnectorMockRecorder is the mock recorder for MockServerConnector.
type MockServerConnectorMockRecorder struct {
	mock *MockServerConnector
}

// NewMockServerConnector creates a new mock instance.
func NewMockServerConnector(ctrl *gomock.Controller) *MockServerConnector {
	mock := &MockServerConnector{ctrl: ctrl}
	mock.recorder = &MockServerConnectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerConnector) EXPECT() *MockServerConnectorMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockServerConnector) Connect(ctx context.Context, url, mode, lang, targetLang string, out io.Writer) (Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx, url, mode, lang, targetLang, out)
	ret0, _ := ret[0].(Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockServerConnectorMockRecorder) Connect(ctx, url, mode, lang, targetLang, out any) *MockServerConnectorConnectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockServerConnector)(nil).Connect), ctx, url, mode, lang, targetLang, out)
	return &MockServerConnectorConnectCall{Call: call}
}

// MockServerConnectorConnectCall wrap *gomock.Call
type MockServerConnectorConnectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServerConnectorConnectCall) Return(arg0 Connection, arg1 error) *MockServerConnectorConnectCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServerConnectorConnectCall) Do(f func(context.Context, string, string, string, string, io.Writer) (Connection, error)) *MockServerConnectorConnectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServerConnectorConnectCall) DoAndReturn(f func(context.Context, string, string, string, string, io.Writer) (Connection, error)) *MockServerConnectorConnectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTyper is a mock of Typer interface.
type MockTyper struct {
	ctrl     *gomock.Controller
	recorder *MockTyperMockRecorder
	isgomock struct{}
}

// MockTyperMockRecorder is the mock recorder for MockTyper.
type MockTyperMockRecorder struct {
	mock *MockTyper
}

// NewMockTyper creates a new mock instance.
func NewMockTyper(ctrl *gomock.Controller) *MockTyper {
	mock := &MockTyper{ctrl: ctrl}
	mock.recorder = &MockTyperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTyper) EXPECT() *MockTyperMockRecorder {
	return m.recorder
}

// Type mocks base method.
func (m *MockTyper) Type(text string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Type", text)
}

// Type indicates an expected call of Type.
func (mr *MockTyperMockRecorder) Type(text any) *MockTyperTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockTyper)(nil).Type), text)
	return &MockTyperTypeCall{Call: call}
}

// MockTyperTypeCall wrap *gomock.Call
type MockTyperTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTyperTypeCall) Return() *MockTyperTypeCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTyperTypeCall) Do(f func(string)) *MockTyperTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTyperTypeCall) DoAndReturn(f func(string)) *MockTyperTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
